[rospy.client][INFO] 2021-01-16 08:23:28,177: init_node, name[/train_1313_1610785408147], pid[1313]
[xmlrpc][INFO] 2021-01-16 08:23:28,178: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-01-16 08:23:28,179: Started XML-RPC server [http://192.168.0.191:36227/]
[rospy.init][INFO] 2021-01-16 08:23:28,179: ROS Slave URI: [http://192.168.0.191:36227/]
[rospy.impl.masterslave][INFO] 2021-01-16 08:23:28,180: _ready: http://192.168.0.191:36227/
[rospy.registration][INFO] 2021-01-16 08:23:28,181: Registering with master node http://192.168.0.126:11311
[xmlrpc][INFO] 2021-01-16 08:23:28,181: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-01-16 08:23:28,280: registered with master
[rospy.rosout][INFO] 2021-01-16 08:23:28,280: initializing /rosout core topic
[rospy.rosout][INFO] 2021-01-16 08:23:28,288: connected to core topic /rosout
[rospy.simtime][INFO] 2021-01-16 08:23:28,290: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2021-01-16 08:23:28,306: topic[/bev/temporal_bev_image] adding connection to [http://192.168.0.126:36903/], count 0
[rospy.internal][INFO] 2021-01-16 08:23:28,310: topic[/odom] adding connection to [http://192.168.0.126:45431/], count 0
[rospy.internal][INFO] 2021-01-16 08:23:28,317: topic[/start_goal_points] adding connection to [http://192.168.0.126:40949/], count 0
[rospy.internal][INFO] 2021-01-16 08:23:28,323: topic[/scan] adding connection to [http://192.168.0.126:45431/], count 0
[rospy.internal][INFO] 2021-01-16 08:23:28,324: topic[/scan] adding connection to [http://192.168.0.126:36669/], count 0
[rospy.internal][INFO] 2021-01-16 08:23:28,330: topic[/is_start_episode] adding connection to [http://192.168.0.126:34007/], count 0
[rospy.internal][INFO] 2021-01-16 08:23:28,478: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2021-01-16 08:23:28,479: topic[/episode_watcher/is_finish_episode] adding connection to [/episode_manager], count 0
[rospy.internal][INFO] 2021-01-16 08:23:28,575: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2021-01-16 08:23:30,921: signal_shutdown [atexit]
[rospy.internal][INFO] 2021-01-16 08:23:30,925: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-01-16 08:23:30,925: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2021-01-16 08:23:30,925: topic[/episode_watcher/is_finish_episode] removing connection to /episode_manager
[rospy.internal][INFO] 2021-01-16 08:23:30,926: topic[/bev/temporal_bev_image] removing connection to http://192.168.0.126:36903/
[rospy.internal][INFO] 2021-01-16 08:23:30,926: topic[/odom] removing connection to http://192.168.0.126:45431/
[rospy.internal][INFO] 2021-01-16 08:23:30,927: topic[/start_goal_points] removing connection to http://192.168.0.126:40949/
[rospy.internal][INFO] 2021-01-16 08:23:30,928: topic[/scan] removing connection to http://192.168.0.126:45431/
[rospy.internal][WARNING] 2021-01-16 08:23:30,929: Unknown error initiating TCP/IP socket to 192.168.0.126:59449 (http://192.168.0.126:36903/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2021-01-16 08:23:30,929: topic[/scan] removing connection to http://192.168.0.126:36669/
[rospy.internal][WARNING] 2021-01-16 08:23:30,929: Unknown error initiating TCP/IP socket to 192.168.0.126:53085 (http://192.168.0.126:36669/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 563, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2021-01-16 08:23:30,930: topic[/is_start_episode] removing connection to http://192.168.0.126:34007/
[rospy.impl.masterslave][INFO] 2021-01-16 08:23:30,931: atexit
[rospy.internal][WARNING] 2021-01-16 08:23:30,931: Unknown error initiating TCP/IP socket to 192.168.0.126:57109 (http://192.168.0.126:34007/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2021-01-16 08:23:30,932: Unknown error initiating TCP/IP socket to 192.168.0.126:35677 (http://192.168.0.126:45431/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 563, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

