[rospy.client][INFO] 2020-12-07 09:48:04,345: init_node, name[/train_648_1607334484306], pid[648]
[xmlrpc][INFO] 2020-12-07 09:48:04,346: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-12-07 09:48:04,347: Started XML-RPC server [http://192.168.0.191:45275/]
[rospy.init][INFO] 2020-12-07 09:48:04,347: ROS Slave URI: [http://192.168.0.191:45275/]
[rospy.impl.masterslave][INFO] 2020-12-07 09:48:04,348: _ready: http://192.168.0.191:45275/
[rospy.registration][INFO] 2020-12-07 09:48:04,349: Registering with master node http://192.168.0.201:11311
[xmlrpc][INFO] 2020-12-07 09:48:04,349: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-12-07 09:48:04,448: registered with master
[rospy.rosout][INFO] 2020-12-07 09:48:04,448: initializing /rosout core topic
[rospy.rosout][INFO] 2020-12-07 09:48:04,456: connected to core topic /rosout
[rospy.simtime][INFO] 2020-12-07 09:48:04,457: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-12-07 09:48:04,469: topic[/bev/flow_array_x] adding connection to [http://192.168.0.201:33953/], count 0
[rospy.internal][INFO] 2020-12-07 09:48:04,474: topic[/bev/flow_array_y] adding connection to [http://192.168.0.201:33953/], count 0
[rospy.internal][INFO] 2020-12-07 09:48:04,478: topic[/bev/raycast_image] adding connection to [http://192.168.0.201:36511/], count 0
[rospy.internal][INFO] 2020-12-07 09:48:04,483: topic[/odom] adding connection to [http://192.168.0.201:43347/], count 0
[rospy.internal][INFO] 2020-12-07 09:48:04,487: topic[/start_goal_points] adding connection to [http://192.168.0.201:37219/], count 0
[rospy.internal][INFO] 2020-12-07 09:48:04,492: topic[/scan] adding connection to [http://192.168.0.201:43347/], count 0
[rospy.internal][INFO] 2020-12-07 09:48:04,495: topic[/scan] adding connection to [http://192.168.0.201:38149/], count 1
[rospy.internal][INFO] 2020-12-07 09:48:04,502: topic[/is_start_episode] adding connection to [http://192.168.0.201:42335/], count 0
[rospy.internal][INFO] 2020-12-07 09:48:04,734: topic[/episode_watcher/is_finish_episode] adding connection to [/episode_manager], count 0
[rospy.internal][INFO] 2020-12-07 09:48:04,749: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-12-07 09:48:04,751: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.core][INFO] 2020-12-07 09:48:10,196: signal_shutdown [atexit]
[rospy.internal][INFO] 2020-12-07 09:48:10,202: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-12-07 09:48:10,203: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2020-12-07 09:48:10,203: topic[/episode_watcher/is_finish_episode] removing connection to /episode_manager
[rospy.internal][INFO] 2020-12-07 09:48:10,204: topic[/bev/flow_array_x] removing connection to http://192.168.0.201:33953/
[rospy.internal][INFO] 2020-12-07 09:48:10,204: topic[/bev/flow_array_y] removing connection to http://192.168.0.201:33953/
[rospy.internal][INFO] 2020-12-07 09:48:10,205: topic[/bev/raycast_image] removing connection to http://192.168.0.201:36511/
[rospy.internal][INFO] 2020-12-07 09:48:10,205: topic[/odom] removing connection to http://192.168.0.201:43347/
[rospy.internal][INFO] 2020-12-07 09:48:10,206: topic[/start_goal_points] removing connection to http://192.168.0.201:37219/
[rospy.internal][WARNING] 2020-12-07 09:48:10,207: Unknown error initiating TCP/IP socket to 192.168.0.201:56405 (http://192.168.0.201:33953/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2020-12-07 09:48:10,207: Unknown error initiating TCP/IP socket to 192.168.0.201:33055 (http://192.168.0.201:43347/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2020-12-07 09:48:10,208: topic[/scan] removing connection to http://192.168.0.201:43347/
[rospy.internal][WARNING] 2020-12-07 09:48:10,209: Unknown error initiating TCP/IP socket to 192.168.0.201:57965 (http://192.168.0.201:36511/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2020-12-07 09:48:10,209: topic[/scan] removing connection to http://192.168.0.201:38149/
[rospy.internal][WARNING] 2020-12-07 09:48:10,209: Unknown error initiating TCP/IP socket to 192.168.0.201:33055 (http://192.168.0.201:43347/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2020-12-07 09:48:10,210: topic[/is_start_episode] removing connection to http://192.168.0.201:42335/
[rospy.impl.masterslave][INFO] 2020-12-07 09:48:10,211: atexit
[rospy.internal][WARNING] 2020-12-07 09:48:10,211: Unknown error initiating TCP/IP socket to 192.168.0.201:58293 (http://192.168.0.201:38149/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

