[rospy.client][INFO] 2020-12-26 05:35:41,731: init_node, name[/train_4884_1608960941701], pid[4884]
[xmlrpc][INFO] 2020-12-26 05:35:41,732: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-12-26 05:35:41,733: Started XML-RPC server [http://192.168.0.191:46095/]
[rospy.init][INFO] 2020-12-26 05:35:41,733: ROS Slave URI: [http://192.168.0.191:46095/]
[rospy.impl.masterslave][INFO] 2020-12-26 05:35:41,733: _ready: http://192.168.0.191:46095/
[rospy.registration][INFO] 2020-12-26 05:35:41,735: Registering with master node http://192.168.0.201:11311
[xmlrpc][INFO] 2020-12-26 05:35:41,735: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-12-26 05:35:41,834: registered with master
[rospy.rosout][INFO] 2020-12-26 05:35:41,834: initializing /rosout core topic
[rospy.rosout][INFO] 2020-12-26 05:35:41,840: connected to core topic /rosout
[rospy.simtime][INFO] 2020-12-26 05:35:41,841: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-12-26 05:35:41,869: topic[/bev/temporal_bev_image] adding connection to [http://192.168.0.201:39549/], count 0
[rospy.internal][INFO] 2020-12-26 05:35:41,871: topic[/is_start_episode] adding connection to [http://192.168.0.201:42987/], count 0
[rospy.internal][INFO] 2020-12-26 05:35:41,873: topic[/scan] adding connection to [http://192.168.0.201:40197/], count 0
[rospy.internal][INFO] 2020-12-26 05:35:41,878: topic[/scan] adding connection to [http://192.168.0.201:37833/], count 1
[rospy.internal][INFO] 2020-12-26 05:35:41,879: topic[/odom] adding connection to [http://192.168.0.201:40197/], count 0
[rospy.internal][INFO] 2020-12-26 05:35:41,879: topic[/start_goal_points] adding connection to [http://192.168.0.201:40835/], count 0
[rospy.internal][INFO] 2020-12-26 05:35:42,057: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-12-26 05:35:42,058: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2020-12-26 05:35:42,059: topic[/episode_watcher/is_finish_episode] adding connection to [/episode_manager], count 0
[rospy.core][INFO] 2020-12-26 05:35:46,824: signal_shutdown [atexit]
[rospy.internal][INFO] 2020-12-26 05:35:46,829: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-12-26 05:35:46,830: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2020-12-26 05:35:46,830: topic[/episode_watcher/is_finish_episode] removing connection to /episode_manager
[rospy.internal][INFO] 2020-12-26 05:35:46,831: topic[/bev/temporal_bev_image] removing connection to http://192.168.0.201:39549/
[rospy.internal][INFO] 2020-12-26 05:35:46,831: topic[/odom] removing connection to http://192.168.0.201:40197/
[rospy.internal][INFO] 2020-12-26 05:35:46,832: topic[/start_goal_points] removing connection to http://192.168.0.201:40835/
[rospy.internal][INFO] 2020-12-26 05:35:46,833: topic[/scan] removing connection to http://192.168.0.201:40197/
[rospy.internal][INFO] 2020-12-26 05:35:46,833: topic[/scan] removing connection to http://192.168.0.201:37833/
[rospy.internal][WARNING] 2020-12-26 05:35:46,834: Unknown error initiating TCP/IP socket to 192.168.0.201:43555 (http://192.168.0.201:39549/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2020-12-26 05:35:46,834: topic[/is_start_episode] removing connection to http://192.168.0.201:42987/
[rospy.impl.masterslave][INFO] 2020-12-26 05:35:46,835: atexit
[rospy.internal][WARNING] 2020-12-26 05:35:46,835: Unknown error initiating TCP/IP socket to 192.168.0.201:60915 (http://192.168.0.201:37833/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2020-12-26 05:35:46,836: Unknown error initiating TCP/IP socket to 192.168.0.201:56385 (http://192.168.0.201:40197/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

