[rospy.client][INFO] 2020-12-23 10:09:16,620: init_node, name[/train_2477_1608718156589], pid[2477]
[xmlrpc][INFO] 2020-12-23 10:09:16,620: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-12-23 10:09:16,621: Started XML-RPC server [http://192.168.0.191:45983/]
[rospy.init][INFO] 2020-12-23 10:09:16,622: ROS Slave URI: [http://192.168.0.191:45983/]
[rospy.impl.masterslave][INFO] 2020-12-23 10:09:16,622: _ready: http://192.168.0.191:45983/
[rospy.registration][INFO] 2020-12-23 10:09:16,623: Registering with master node http://192.168.0.201:11311
[xmlrpc][INFO] 2020-12-23 10:09:16,623: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-12-23 10:09:16,722: registered with master
[rospy.rosout][INFO] 2020-12-23 10:09:16,722: initializing /rosout core topic
[rospy.rosout][INFO] 2020-12-23 10:09:16,728: connected to core topic /rosout
[rospy.simtime][INFO] 2020-12-23 10:09:16,730: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-12-23 10:09:16,755: topic[/bev/temporal_bev_image] adding connection to [http://192.168.0.201:38273/], count 0
[rospy.internal][INFO] 2020-12-23 10:09:16,761: topic[/is_start_episode] adding connection to [http://192.168.0.201:38289/], count 0
[rospy.internal][INFO] 2020-12-23 10:09:16,764: topic[/scan] adding connection to [http://192.168.0.201:39961/], count 0
[rospy.internal][INFO] 2020-12-23 10:09:16,769: topic[/scan] adding connection to [http://192.168.0.201:41653/], count 1
[rospy.internal][INFO] 2020-12-23 10:09:16,769: topic[/odom] adding connection to [http://192.168.0.201:39961/], count 0
[rospy.internal][INFO] 2020-12-23 10:09:16,770: topic[/start_goal_points] adding connection to [http://192.168.0.201:33305/], count 0
[rospy.internal][INFO] 2020-12-23 10:09:16,944: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-12-23 10:09:16,945: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2020-12-23 10:09:16,946: topic[/episode_watcher/is_finish_episode] adding connection to [/episode_manager], count 0
[rospy.core][INFO] 2020-12-23 10:09:26,304: signal_shutdown [atexit]
[rospy.internal][INFO] 2020-12-23 10:09:26,310: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-12-23 10:09:26,310: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2020-12-23 10:09:26,310: topic[/episode_watcher/is_finish_episode] removing connection to /episode_manager
[rospy.internal][INFO] 2020-12-23 10:09:26,311: topic[/bev/temporal_bev_image] removing connection to http://192.168.0.201:38273/
[rospy.internal][INFO] 2020-12-23 10:09:26,312: topic[/odom] removing connection to http://192.168.0.201:39961/
[rospy.internal][INFO] 2020-12-23 10:09:26,313: topic[/start_goal_points] removing connection to http://192.168.0.201:33305/
[rospy.internal][WARNING] 2020-12-23 10:09:26,313: Unknown error initiating TCP/IP socket to 192.168.0.201:50065 (http://192.168.0.201:38273/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2020-12-23 10:09:26,314: topic[/scan] removing connection to http://192.168.0.201:39961/
[rospy.internal][WARNING] 2020-12-23 10:09:26,315: Unknown error initiating TCP/IP socket to 192.168.0.201:46965 (http://192.168.0.201:39961/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2020-12-23 10:09:26,315: Unknown error initiating TCP/IP socket to 192.168.0.201:53965 (http://192.168.0.201:33305/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2020-12-23 10:09:26,316: Unknown error initiating TCP/IP socket to 192.168.0.201:46965 (http://192.168.0.201:39961/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.topics][ERROR] 2020-12-23 10:09:26,317: Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/topics.py", line 326, in close
    c.close()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 846, in close
    self.socket.close()
AttributeError: 'NoneType' object has no attribute 'close'

[rospy.internal][INFO] 2020-12-23 10:09:26,317: topic[/scan] removing connection to http://192.168.0.201:41653/
[rospy.internal][INFO] 2020-12-23 10:09:26,318: topic[/is_start_episode] removing connection to http://192.168.0.201:38289/
[rospy.impl.masterslave][INFO] 2020-12-23 10:09:26,318: atexit
[rospy.internal][WARNING] 2020-12-23 10:09:26,318: Unknown error initiating TCP/IP socket to 192.168.0.201:44457 (http://192.168.0.201:38289/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

