[rospy.client][INFO] 2020-12-23 10:05:54,491: init_node, name[/train_2127_1608717954463], pid[2127]
[xmlrpc][INFO] 2020-12-23 10:05:54,491: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-12-23 10:05:54,492: Started XML-RPC server [http://192.168.0.191:39739/]
[rospy.init][INFO] 2020-12-23 10:05:54,492: ROS Slave URI: [http://192.168.0.191:39739/]
[rospy.impl.masterslave][INFO] 2020-12-23 10:05:54,492: _ready: http://192.168.0.191:39739/
[rospy.registration][INFO] 2020-12-23 10:05:54,494: Registering with master node http://192.168.0.201:11311
[xmlrpc][INFO] 2020-12-23 10:05:54,494: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-12-23 10:05:54,593: registered with master
[rospy.rosout][INFO] 2020-12-23 10:05:54,593: initializing /rosout core topic
[rospy.rosout][INFO] 2020-12-23 10:05:54,598: connected to core topic /rosout
[rospy.simtime][INFO] 2020-12-23 10:05:54,599: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-12-23 10:05:54,612: topic[/bev/temporal_bev_image] adding connection to [http://192.168.0.201:38273/], count 0
[rospy.internal][INFO] 2020-12-23 10:05:54,618: topic[/start_goal_points] adding connection to [http://192.168.0.201:33305/], count 0
[rospy.internal][INFO] 2020-12-23 10:05:54,622: topic[/is_start_episode] adding connection to [http://192.168.0.201:38289/], count 0
[rospy.internal][INFO] 2020-12-23 10:05:54,627: topic[/scan] adding connection to [http://192.168.0.201:39961/], count 0
[rospy.internal][INFO] 2020-12-23 10:05:54,629: topic[/scan] adding connection to [http://192.168.0.201:41653/], count 1
[rospy.internal][INFO] 2020-12-23 10:05:54,631: topic[/odom] adding connection to [http://192.168.0.201:39961/], count 0
[rospy.internal][INFO] 2020-12-23 10:05:54,837: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-12-23 10:05:54,838: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2020-12-23 10:05:54,839: topic[/episode_watcher/is_finish_episode] adding connection to [/episode_manager], count 0
[rospy.core][INFO] 2020-12-23 10:05:56,907: signal_shutdown [atexit]
[rospy.internal][INFO] 2020-12-23 10:05:56,911: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-12-23 10:05:56,911: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2020-12-23 10:05:56,911: topic[/episode_watcher/is_finish_episode] removing connection to /episode_manager
[rospy.internal][INFO] 2020-12-23 10:05:56,911: topic[/bev/temporal_bev_image] removing connection to http://192.168.0.201:38273/
[rospy.internal][INFO] 2020-12-23 10:05:56,912: topic[/odom] removing connection to http://192.168.0.201:39961/
[rospy.internal][INFO] 2020-12-23 10:05:56,912: topic[/start_goal_points] removing connection to http://192.168.0.201:33305/
[rospy.internal][INFO] 2020-12-23 10:05:56,913: topic[/scan] removing connection to http://192.168.0.201:39961/
[rospy.internal][INFO] 2020-12-23 10:05:56,913: topic[/scan] removing connection to http://192.168.0.201:41653/
[rospy.internal][WARNING] 2020-12-23 10:05:56,914: Unknown error initiating TCP/IP socket to 192.168.0.201:50065 (http://192.168.0.201:38273/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2020-12-23 10:05:56,914: topic[/is_start_episode] removing connection to http://192.168.0.201:38289/
[rospy.internal][WARNING] 2020-12-23 10:05:56,915: Unknown error initiating TCP/IP socket to 192.168.0.201:53267 (http://192.168.0.201:41653/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2020-12-23 10:05:56,915: Unknown error initiating TCP/IP socket to 192.168.0.201:46965 (http://192.168.0.201:39961/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.impl.masterslave][INFO] 2020-12-23 10:05:56,915: atexit
