[rospy.client][INFO] 2021-01-16 08:49:06,417: init_node, name[/train_1795_1610786946387], pid[1795]
[xmlrpc][INFO] 2021-01-16 08:49:06,418: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-01-16 08:49:06,419: Started XML-RPC server [http://192.168.0.191:37541/]
[rospy.init][INFO] 2021-01-16 08:49:06,419: ROS Slave URI: [http://192.168.0.191:37541/]
[rospy.impl.masterslave][INFO] 2021-01-16 08:49:06,419: _ready: http://192.168.0.191:37541/
[rospy.registration][INFO] 2021-01-16 08:49:06,421: Registering with master node http://192.168.0.126:11311
[xmlrpc][INFO] 2021-01-16 08:49:06,421: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-01-16 08:49:06,520: registered with master
[rospy.rosout][INFO] 2021-01-16 08:49:06,520: initializing /rosout core topic
[rospy.rosout][INFO] 2021-01-16 08:49:06,527: connected to core topic /rosout
[rospy.simtime][INFO] 2021-01-16 08:49:06,529: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2021-01-16 08:49:06,542: topic[/bev/temporal_bev_image] adding connection to [http://192.168.0.126:36903/], count 0
[rospy.internal][INFO] 2021-01-16 08:49:06,547: topic[/odom] adding connection to [http://192.168.0.126:45431/], count 0
[rospy.internal][INFO] 2021-01-16 08:49:06,552: topic[/start_goal_points] adding connection to [http://192.168.0.126:40949/], count 0
[rospy.internal][INFO] 2021-01-16 08:49:06,559: topic[/scan] adding connection to [http://192.168.0.126:36669/], count 0
[rospy.internal][INFO] 2021-01-16 08:49:06,560: topic[/scan] adding connection to [http://192.168.0.126:45431/], count 1
[rospy.internal][INFO] 2021-01-16 08:49:06,565: topic[/is_start_episode] adding connection to [http://192.168.0.126:34007/], count 0
[rospy.internal][INFO] 2021-01-16 08:49:06,731: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2021-01-16 08:49:06,732: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2021-01-16 08:49:06,832: topic[/episode_watcher/is_finish_episode] adding connection to [/episode_manager], count 0
[rospy.core][INFO] 2021-01-16 08:49:09,071: signal_shutdown [atexit]
[rospy.internal][INFO] 2021-01-16 08:49:09,075: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-01-16 08:49:09,075: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2021-01-16 08:49:09,076: topic[/episode_watcher/is_finish_episode] removing connection to /episode_manager
[rospy.internal][INFO] 2021-01-16 08:49:09,076: topic[/bev/temporal_bev_image] removing connection to http://192.168.0.126:36903/
[rospy.internal][INFO] 2021-01-16 08:49:09,077: topic[/odom] removing connection to http://192.168.0.126:45431/
[rospy.internal][INFO] 2021-01-16 08:49:09,077: topic[/start_goal_points] removing connection to http://192.168.0.126:40949/
[rospy.internal][INFO] 2021-01-16 08:49:09,078: topic[/scan] removing connection to http://192.168.0.126:36669/
[rospy.internal][INFO] 2021-01-16 08:49:09,079: topic[/scan] removing connection to http://192.168.0.126:45431/
[rospy.internal][WARNING] 2021-01-16 08:49:09,080: Unknown error initiating TCP/IP socket to 192.168.0.126:35677 (http://192.168.0.126:45431/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2021-01-16 08:49:09,081: topic[/is_start_episode] removing connection to http://192.168.0.126:34007/
[rospy.internal][WARNING] 2021-01-16 08:49:09,081: Unknown error initiating TCP/IP socket to 192.168.0.126:35677 (http://192.168.0.126:45431/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 563, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][WARNING] 2021-01-16 08:49:09,081: Unknown error initiating TCP/IP socket to 192.168.0.126:59449 (http://192.168.0.126:36903/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.impl.masterslave][INFO] 2021-01-16 08:49:09,081: atexit
[rospy.internal][WARNING] 2021-01-16 08:49:09,082: Unknown error initiating TCP/IP socket to 192.168.0.126:53085 (http://192.168.0.126:36669/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][WARNING] 2021-01-16 08:49:09,082: Unknown error initiating TCP/IP socket to 192.168.0.126:57109 (http://192.168.0.126:34007/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 563, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

