[rospy.client][INFO] 2021-01-06 03:21:46,389: init_node, name[/train_1560_1609903306369], pid[1560]
[xmlrpc][INFO] 2021-01-06 03:21:46,390: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-01-06 03:21:46,390: Started XML-RPC server [http://192.168.0.162:41521/]
[rospy.init][INFO] 2021-01-06 03:21:46,390: ROS Slave URI: [http://192.168.0.162:41521/]
[rospy.impl.masterslave][INFO] 2021-01-06 03:21:46,390: _ready: http://192.168.0.162:41521/
[rospy.registration][INFO] 2021-01-06 03:21:46,390: Registering with master node http://192.168.0.201:11311
[xmlrpc][INFO] 2021-01-06 03:21:46,390: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2021-01-06 03:21:46,490: registered with master
[rospy.rosout][INFO] 2021-01-06 03:21:46,490: initializing /rosout core topic
[rospy.rosout][INFO] 2021-01-06 03:21:46,496: connected to core topic /rosout
[rospy.simtime][INFO] 2021-01-06 03:21:46,498: initializing /clock core topic
[rospy.simtime][INFO] 2021-01-06 03:21:46,502: connected to core topic /clock
[rospy.internal][INFO] 2021-01-06 03:21:46,504: topic[/clock] adding connection to [http://192.168.0.201:40983/], count 0
[rospy.internal][INFO] 2021-01-06 03:21:46,509: topic[/bev/temporal_bev_image] adding connection to [http://192.168.0.201:44187/], count 0
[rospy.internal][INFO] 2021-01-06 03:21:46,511: topic[/odom] adding connection to [http://192.168.0.201:40983/], count 0
[rospy.internal][INFO] 2021-01-06 03:21:46,513: topic[/start_goal_points] adding connection to [http://192.168.0.201:42893/], count 0
[rospy.internal][INFO] 2021-01-06 03:21:46,518: topic[/scan] adding connection to [http://192.168.0.201:44413/], count 0
[rospy.internal][INFO] 2021-01-06 03:21:46,520: topic[/scan] adding connection to [http://192.168.0.201:40983/], count 1
[rospy.internal][INFO] 2021-01-06 03:21:46,521: topic[/is_start_episode] adding connection to [http://192.168.0.201:35999/], count 0
[rospy.internal][INFO] 2021-01-06 03:21:46,700: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2021-01-06 03:21:46,700: topic[/cmd_vel] adding connection to [/gazebo], count 0
[rospy.internal][INFO] 2021-01-06 03:21:46,701: topic[/episode_watcher/is_finish_episode] adding connection to [/episode_manager], count 0
[rospy.core][INFO] 2021-01-06 03:21:48,133: signal_shutdown [atexit]
[rospy.internal][INFO] 2021-01-06 03:21:48,136: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-01-06 03:21:48,136: topic[/cmd_vel] removing connection to /gazebo
[rospy.internal][INFO] 2021-01-06 03:21:48,136: topic[/episode_watcher/is_finish_episode] removing connection to /episode_manager
[rospy.internal][INFO] 2021-01-06 03:21:48,137: topic[/clock] removing connection to http://192.168.0.201:40983/
[rospy.internal][INFO] 2021-01-06 03:21:48,137: topic[/bev/temporal_bev_image] removing connection to http://192.168.0.201:44187/
[rospy.internal][INFO] 2021-01-06 03:21:48,137: topic[/odom] removing connection to http://192.168.0.201:40983/
[rospy.internal][INFO] 2021-01-06 03:21:48,137: topic[/start_goal_points] removing connection to http://192.168.0.201:42893/
[rospy.internal][WARNING] 2021-01-06 03:21:48,138: Unknown error initiating TCP/IP socket to 192.168.0.201:45043 (http://192.168.0.201:40983/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2021-01-06 03:21:48,138: topic[/scan] removing connection to http://192.168.0.201:44413/
[rospy.internal][WARNING] 2021-01-06 03:21:48,138: Unknown error initiating TCP/IP socket to 192.168.0.201:45043 (http://192.168.0.201:40983/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 563, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][WARNING] 2021-01-06 03:21:48,138: Unknown error initiating TCP/IP socket to 192.168.0.201:33161 (http://192.168.0.201:44413/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 563, in connect
    self.local_endpoint = self.socket.getsockname()
AttributeError: 'NoneType' object has no attribute 'getsockname'

[rospy.internal][INFO] 2021-01-06 03:21:48,138: topic[/scan] removing connection to http://192.168.0.201:40983/
[rospy.internal][INFO] 2021-01-06 03:21:48,139: topic[/is_start_episode] removing connection to http://192.168.0.201:35999/
[rospy.impl.masterslave][INFO] 2021-01-06 03:21:48,139: atexit
[rospy.internal][WARNING] 2021-01-06 03:21:48,139: Unknown error initiating TCP/IP socket to 192.168.0.201:45043 (http://192.168.0.201:40983/): Traceback (most recent call last):
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/noetic/lib/python3/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

